version: "3.8"

services:
  app:
    depends_on:
      - postgres
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
  postgres:
    container_name: postgres
    image: postgres:14
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
      PG_DATA: /var/lib/postgresql/data
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
